# ABOUTME: golangci-lint configuration for mammoth.
# ABOUTME: Enables core linters with sensible defaults, avoids noisy rules.
version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (io.Writer).Write
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - (*encoding/json.Decoder).Decode
        - fmt.Fprintf
        - fmt.Fprintln
    govet:
      disable:
        - fieldalignment
        - shadow
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters: [errcheck]
        path: _test\.go
      - linters: [unused]
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 5
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
