# ABOUTME: golangci-lint configuration for makeatron.
# ABOUTME: Enables core linters with sensible defaults, avoids noisy rules.

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - godot
    - godox
    - gomnd
    - lll
    - nestif
    - nlreturn
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  staticcheck:
    checks:
      - all

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 5
