// ABOUTME: Web handlers for exporting specs as Markdown and YAML files.
// ABOUTME: Serves both in-page artifact views and downloadable file attachments.
package web

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/2389-research/mammoth/spec/core"
	"github.com/2389-research/mammoth/spec/export"
	"github.com/2389-research/mammoth/spec/server"
)

// ArtifactsData is the view-model for the artifacts tab partial.
type ArtifactsData struct {
	SpecID          string
	MarkdownContent string
	YAMLContent     string
	DOTContent      string
}

// Artifacts renders the artifacts tab with all three export formats.
func Artifacts(state *server.AppState, renderer *TemplateRenderer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		specID, ok := parseSpecID(w, r)
		if !ok {
			return
		}

		handle := state.GetActor(specID)
		if handle == nil {
			writeHTMLError(w, http.StatusNotFound, "Spec not found.")
			return
		}

		var data ArtifactsData
		handle.ReadState(func(s *core.SpecState) {
			data.SpecID = specID.String()
			data.MarkdownContent = export.ExportMarkdown(s)
			yamlContent, err := export.ExportYAML(s)
			if err != nil {
				data.YAMLContent = fmt.Sprintf("# YAML export error: %v", err)
			} else {
				data.YAMLContent = yamlContent
			}
			// DOT is generated by the meta-pipeline, not deterministically from spec state.
			data.DOTContent = ""
		})

		renderer.RenderPartial(w, "artifacts.html", data)
	}
}

// ExportMarkdown serves the spec as a downloadable Markdown file.
func ExportMarkdown(state *server.AppState) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		specID, ok := parseSpecID(w, r)
		if !ok {
			return
		}

		handle := state.GetActor(specID)
		if handle == nil {
			writeHTMLError(w, http.StatusNotFound, "Spec not found.")
			return
		}

		var content string
		handle.ReadState(func(s *core.SpecState) {
			content = export.ExportMarkdown(s)
		})

		w.Header().Set("Content-Type", "text/markdown")
		w.Header().Set("Content-Disposition", `attachment; filename="spec.md"`)
		w.WriteHeader(http.StatusOK)
		_, _ = fmt.Fprint(w, content)
	}
}

// ExportYAML serves the spec as a downloadable YAML file.
func ExportYAML(state *server.AppState) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		specID, ok := parseSpecID(w, r)
		if !ok {
			return
		}

		handle := state.GetActor(specID)
		if handle == nil {
			writeHTMLError(w, http.StatusNotFound, "Spec not found.")
			return
		}

		var content string
		var exportErr error
		handle.ReadState(func(s *core.SpecState) {
			content, exportErr = export.ExportYAML(s)
		})

		if exportErr != nil {
			log.Printf("YAML export failed for spec %s: %v", specID, exportErr)
			writeHTMLError(w, http.StatusInternalServerError, "Failed to export YAML.")
			return
		}

		w.Header().Set("Content-Type", "text/yaml")
		w.Header().Set("Content-Disposition", `attachment; filename="spec.yaml"`)
		w.WriteHeader(http.StatusOK)
		_, _ = fmt.Fprint(w, content)
	}
}

// Regenerate exports Markdown and YAML formats to disk and returns a confirmation HTML snippet.
func Regenerate(state *server.AppState) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		specID, ok := parseSpecID(w, r)
		if !ok {
			return
		}

		handle := state.GetActor(specID)
		if handle == nil {
			writeHTMLError(w, http.StatusNotFound, "Spec not found.")
			return
		}

		var markdownContent, yamlContent string
		var specTitle string
		handle.ReadState(func(s *core.SpecState) {
			markdownContent = export.ExportMarkdown(s)
			yaml, err := export.ExportYAML(s)
			if err != nil {
				yamlContent = fmt.Sprintf("# YAML export error: %v", err)
			} else {
				yamlContent = yaml
			}
			if s.Core != nil {
				specTitle = s.Core.Title
			}
		})

		if specTitle == "" {
			specTitle = "spec"
		}

		// Write to $MAMMOTH_HOME/specs/<spec_id>/exports/
		exportsDir := filepath.Join(state.MammothHome, "specs", specID.String(), "exports")
		if err := os.MkdirAll(exportsDir, 0o755); err != nil {
			log.Printf("failed to create exports directory: %v", err)
		} else {
			slug := toSlug(specTitle)
			if err := os.WriteFile(filepath.Join(exportsDir, slug+".md"), []byte(markdownContent), 0o644); err != nil {
				log.Printf("failed to write markdown export: %v", err)
			}
			if err := os.WriteFile(filepath.Join(exportsDir, slug+".yaml"), []byte(yamlContent), 0o644); err != nil {
				log.Printf("failed to write YAML export: %v", err)
			}
			log.Printf("regenerated exports for spec %s at %s", specID, exportsDir)
		}

		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusOK)
		_, _ = fmt.Fprint(w, `<span class="regen-confirm">Exports saved successfully.</span>`)
	}
}

// toSlug converts a title to a URL-safe slug for filenames.
func toSlug(title string) string {
	var result strings.Builder
	for _, ch := range strings.ToLower(title) {
		if (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '-' || ch == '_' {
			result.WriteRune(ch)
		} else {
			result.WriteRune('-')
		}
	}
	slug := result.String()
	// Trim trailing hyphens
	slug = strings.TrimRight(slug, "-")
	if slug == "" {
		return "spec"
	}
	return slug
}
